version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running tests"
  
  build:
    commands:
      - echo "Building the application"
      - python test_train_model.py
      - echo "Testing Complete"

  post_build:
    commands:
      - echo "Build phase Complete"

artifacts:
  files:
    - '**/*'
  discard-paths: no  
